techup_dbt_hands_on_lab:
  target: prod
  outputs:
    prod:
      type: snowflake
      role: TECHUP25_RL
      warehouse: TECHUP25_WH
      database: TECHUP25
      schema: PUBLIC
      account: ''
      user: ''