USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS TECHUP25TECHUP25TECHUP25;
CREATE WAREHOUSE IF NOT EXISTS TECHUP25_WH;
CREATE ROLE IF NOT EXISTS TECHUP25_RL;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TECHUP25_RL;
GRANT ALL ON DATABASE TECHUP25 TO ROLE TECHUP25_RL;
GRANT ALL ON WAREHOUSE TECHUP25_WH TO ROLE TECHUP25_RL;

GRANT ROLE TECHUP25_RL TO ROLE SYSADMIN;
SET current_user_name = CURRENT_USER();
GRANT ROLE TECHUP25_RL TO USER IDENTIFIER($current_user_name);

-- DBT specific scripts here
-- Following dbt standard schema convention:
-- Target schema: DBT_HOL
-- Custom schema 1: SILVER (i.e. becomes DBT_HOL_SILVER)
-- Custom schema 2: GOLD (i.e. becomes DBT_HOL_GOLD)
USE DATABASE TECHUP25;
CREATE SCHEMA IF NOT EXISTS DBT_HOL_SILVER;
CREATE SCHEMA IF NOT EXISTS DBT_HOL_GOLD;

-- dbt Transformer Role
CREATE DATABASE ROLE IF NOT EXISTS DBT_HOL_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA DBT_HOL_SILVER TO DATABASE ROLE DBT_HOL_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_TRANSFORM;

-- Reader role for SiS app
CREATE DATABASE ROLE IF NOT EXISTS DBT_HOL_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_READER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_READER;

-- Schema for storing DBT Projects & Streamlit
CREATE SCHEMA PROJECTS;
GRANT USAGE ON SCHEMA PROJECTS TO DATABASE ROLE DBT_HOL_TRANSFORM;
GRANT CREATE DBT PROJECT ON SCHEMA PROJECTS TO DATABASE ROLE DBT_HOL_TRANSFORM;
GRANT CREATE STREAMLIT ON SCHEMA PROJECTS TO DATABASE ROLE DBT_HOL_READER;

GRANT DATABASE ROLE DBT_HOL_TRANSFORM TO ROLE TECHUP25_RL;
GRANT DATABASE ROLE DBT_HOL_READER TO ROLE TECHUP25_RL;


CREATE OR REPLACE API INTEGRATION my_git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/<GITHUB_USERNAME>')
  ENABLED = TRUE;