USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS TECHUP25TECHUP25TECHUP25;
CREATE WAREHOUSE IF NOT EXISTS TECHUP25_WH;
CREATE ROLE IF NOT EXISTS TECHUP25_RL;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TECHUP25_RL;
GRANT ALL ON DATABASE TECHUP25 TO ROLE TECHUP25_RL;
GRANT ALL ON WAREHOUSE TECHUP25_WH TO ROLE TECHUP25_RL;

GRANT ROLE TECHUP25_RL TO ROLE SYSADMIN;
SET current_user_name = CURRENT_USER();
GRANT ROLE TECHUP25_RL TO USER IDENTIFIER($current_user_name);

-- DBT specific scripts here
-- Following dbt standard schema convention:
-- Target schema: DBT_HOL
-- Custom schema 1: SILVER (i.e. becomes DBT_HOL_SILVER)
-- Custom schema 2: GOLD (i.e. becomes DBT_HOL_GOLD)
USE DATABASE TECHUP25;
CREATE SCHEMA IF NOT EXISTS DBT_HOL_SILVER;
CREATE SCHEMA IF NOT EXISTS DBT_HOL_GOLD;

-- dbt Transformer Role
CREATE DATABASE ROLE IF NOT EXISTS DBT_HOL_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA DBT_HOL_SILVER TO DATABASE ROLE DBT_HOL_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_TRANSFORM;

-- Reader role for SiS app
CREATE DATABASE ROLE IF NOT EXISTS DBT_HOL_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_READER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA DBT_HOL_GOLD TO DATABASE ROLE DBT_HOL_READER;

-- Schema for storing DBT Projects & Streamlit
CREATE SCHEMA PROJECTS;
GRANT USAGE ON SCHEMA PROJECTS TO DATABASE ROLE DBT_HOL_TRANSFORM;
GRANT CREATE DBT PROJECT ON SCHEMA PROJECTS TO DATABASE ROLE DBT_HOL_TRANSFORM;
GRANT CREATE STREAMLIT ON SCHEMA PROJECTS TO DATABASE ROLE DBT_HOL_READER;

GRANT DATABASE ROLE DBT_HOL_TRANSFORM TO ROLE TECHUP25_RL;
GRANT DATABASE ROLE DBT_HOL_READER TO ROLE TECHUP25_RL;

-- Create NETWORK RULE for external access integration
CREATE OR REPLACE NETWORK RULE dbt_network_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  -- Minimal URL allowlist that is required for dbt deps
  VALUE_LIST = (
    'hub.getdbt.com',
    'codeload.github.com'
    );

-- Create EXTERNAL ACCESS INTEGRATION for dbt access to external dbt package locations
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION dbt_ext_access
  ALLOWED_NETWORK_RULES = (dbt_network_rule)
  ENABLED = TRUE;