select * from TECHUP25.DBT_HOL_SILVER.TAXI_AVAILABILITY limit 100;
select * from TECHUP25.DBT_HOL_SILVER.HAWKER_CENTRES order by name;

select st_distance()
from TECHUP25.DBT_HOL_SILVER.TAXI_AVAILABILITY ta;

select *
from APJ_TECHUP_FY26__SINGAPORE_TAXI_DATASET.RAW_DATA.LTA_MRT_STATION_EXIT
